// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Transfer.Dal.Context;

namespace Transfer.Dal.Migrations
{
    [DbContext(typeof(TransferContext))]
    partial class TransferContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:IdentityIncrement", 1)
                .HasAnnotation("SqlServer:IdentitySeed", 1)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Transfer.Dal.Entities.DbAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("LastUpdateTick")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("PersonDataId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId");

                    b.HasIndex("PersonDataId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Transfer.Dal.Entities.DbAccountRight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("LastUpdateTick")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RightId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RightId");

                    b.HasIndex("AccountId", "RightId", "OrganisationId")
                        .IsUnique()
                        .HasFilter("[AccountId] IS NOT NULL AND [RightId] IS NOT NULL AND [OrganisationId] IS NOT NULL");

                    b.ToTable("AccountRights");
                });

            modelBuilder.Entity("Transfer.Dal.Entities.DbDriver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DbDriversLicenseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("LastUpdateTick")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("PersonDataId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TelegramId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DbDriversLicenseId");

                    b.HasIndex("PersonDataId");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("Transfer.Dal.Entities.DbDriversLicense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DocumentCatigories")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("DocumentDateOfIssue")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DocumentEndDateOfIssue")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentIssurer")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DocumentSeries")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("LastUpdateTick")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("DriverLicenses");
                });

            modelBuilder.Entity("Transfer.Dal.Entities.DbExternalLogin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("LastUpdateTick")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LoginType")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SubValue")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("ExternalLogins");
                });

            modelBuilder.Entity("Transfer.Dal.Entities.DbOrganisation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DirectorFio")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DirectorPosition")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("INN")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("LastUpdateTick")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("OGRN")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("RegionId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("Organisations");
                });

            modelBuilder.Entity("Transfer.Dal.Entities.DbOrganisationWorkingArea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("LastUpdateTick")
                        .HasColumnType("bigint");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId");

                    b.HasIndex("RegionId");

                    b.ToTable("OrganisationWorkingAreas");
                });

            modelBuilder.Entity("Transfer.Dal.Entities.DbPersonData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DocumentDateOfIssue")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentIssurer")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DocumentSeries")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DocumentSubDivisionCode")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsMale")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("LastUpdateTick")
                        .HasColumnType("bigint");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PlaceOfBirth")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("RealAddress")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("RegistrationAddress")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("PersonDatas");
                });

            modelBuilder.Entity("Transfer.Dal.Entities.DbRegion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("LastUpdateTick")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("Transfer.Dal.Entities.DbRight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("LastUpdateTick")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("Rights");
                });

            modelBuilder.Entity("Transfer.Dal.Entities.DbAccount", b =>
                {
                    b.HasOne("Transfer.Dal.Entities.DbOrganisation", "Organisation")
                        .WithMany("Accounts")
                        .HasForeignKey("OrganisationId");

                    b.HasOne("Transfer.Dal.Entities.DbPersonData", "PersonData")
                        .WithMany("Accounts")
                        .HasForeignKey("PersonDataId");

                    b.Navigation("Organisation");

                    b.Navigation("PersonData");
                });

            modelBuilder.Entity("Transfer.Dal.Entities.DbAccountRight", b =>
                {
                    b.HasOne("Transfer.Dal.Entities.DbAccount", "Account")
                        .WithMany("AccountRights")
                        .HasForeignKey("AccountId");

                    b.HasOne("Transfer.Dal.Entities.DbRight", "Right")
                        .WithMany("AccountRights")
                        .HasForeignKey("RightId");

                    b.Navigation("Account");

                    b.Navigation("Right");
                });

            modelBuilder.Entity("Transfer.Dal.Entities.DbDriver", b =>
                {
                    b.HasOne("Transfer.Dal.Entities.DbDriversLicense", "DriversLicense")
                        .WithMany("Drivers")
                        .HasForeignKey("DbDriversLicenseId");

                    b.HasOne("Transfer.Dal.Entities.DbPersonData", "PersonData")
                        .WithMany("DriversData")
                        .HasForeignKey("PersonDataId");

                    b.Navigation("DriversLicense");

                    b.Navigation("PersonData");
                });

            modelBuilder.Entity("Transfer.Dal.Entities.DbExternalLogin", b =>
                {
                    b.HasOne("Transfer.Dal.Entities.DbAccount", "Account")
                        .WithMany("ExternalLogins")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Transfer.Dal.Entities.DbOrganisation", b =>
                {
                    b.HasOne("Transfer.Dal.Entities.DbRegion", "Region")
                        .WithMany("Organisations")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Transfer.Dal.Entities.DbOrganisationWorkingArea", b =>
                {
                    b.HasOne("Transfer.Dal.Entities.DbOrganisation", "Organisation")
                        .WithMany("WorkingArea")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Transfer.Dal.Entities.DbRegion", "Region")
                        .WithMany("WorkingArea")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organisation");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Transfer.Dal.Entities.DbAccount", b =>
                {
                    b.Navigation("AccountRights");

                    b.Navigation("ExternalLogins");
                });

            modelBuilder.Entity("Transfer.Dal.Entities.DbDriversLicense", b =>
                {
                    b.Navigation("Drivers");
                });

            modelBuilder.Entity("Transfer.Dal.Entities.DbOrganisation", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("WorkingArea");
                });

            modelBuilder.Entity("Transfer.Dal.Entities.DbPersonData", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("DriversData");
                });

            modelBuilder.Entity("Transfer.Dal.Entities.DbRegion", b =>
                {
                    b.Navigation("Organisations");

                    b.Navigation("WorkingArea");
                });

            modelBuilder.Entity("Transfer.Dal.Entities.DbRight", b =>
                {
                    b.Navigation("AccountRights");
                });
#pragma warning restore 612, 618
        }
    }
}
